In [1]:
import pandas as pd

In [2]:
from google.colab import files

In [6]:
uploaded=files.upload()

Saving cars data.csv to cars data.csv

In [9]:
df=pd.read_csv('cars data.csv')
df

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         428 non-null    object
 1   Model        428 non-null    object
 2   Type         428 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      428 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   428 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
dtypes: float64(8), object(7)
memory usage: 50.8+ KB

In [12]:
df.shape

(432, 15)

In [13]:
df.columns

Index(['Make', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP', 'Invoice',
       'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City', 'MPG_Highway',
       'Weight', 'Wheelbase', 'Length'],
      dtype='object')

In [14]:
df.isnull().sum()

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [16]:
df=df.dropna(subset=['Make','Model','Type','Origin','DriveTrain','MSRP','Invoice','EngineSize','Cylinders','Horsepower','MPG_City','MPG_Highway','Weight','Wheelbase','Length'])

In [18]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
427    False
428    False
429    False
430    False
431    False
Length: 426, dtype: bool

In [20]:
df.drop_duplicates()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

In [22]:
df.describe()

,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000
mean,3.205634,5.807512,215.877934,20.070423,26.854460,3580.474178,108.164319,186.420188
std,1.103520,1.558443,71.991040,5.248616,5.752335,759.870073,8.330030,14.366611
min,1.400000,3.000000,73.000000,10.000000,12.000000,1850.000000,89.000000,143.000000
25%,2.400000,4.000000,165.000000,17.000000,24.000000,3111.250000,103.000000,178.000000
50%,3.000000,6.000000,210.000000,19.000000,26.000000,3476.000000,107.000000,187.000000
75%,3.900000,6.000000,255.000000,21.750000,29.000000,3979.250000,112.000000,194.000000
max,8.300000,12.000000,500.000000,60.000000,66.000000,7190.000000,144.000000,238.000000

#connect sql

In [23]:
import pandas as pd
import sqlite3

In [25]:
df=pd.read_csv('cars data.csv')
df

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0
430,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0
431,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0

#create sqlite database

In [26]:
conn = sqlite3.connect("cars.db")

#upload database in sqlite

In [27]:
df.to_sql(
    "cars",
    conn,
    if_exists="replace",
    index=False
)

432

#check data is uploaded in sqlite

In [28]:
query = """
SELECT *
FROM cars
LIMIT 10;
"""

pd.read_sql_query(query, conn)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225.0,18.0,24.0,3893.0,115.0,197.0
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290.0,17.0,24.0,3153.0,100.0,174.0
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170.0,22.0,31.0,3252.0,104.0,179.0
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170.0,23.0,30.0,3638.0,105.0,180.0
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220.0,20.0,28.0,3462.0,104.0,179.0

#total recods

In [29]:
pd.read_sql_query(
    "SELECT COUNT(*) AS total_records FROM cars;",
    conn
)

   total_records
0            432

#check sqlite table

In [30]:
pd.read_sql_query(
    "PRAGMA table_info(cars);",
    conn
)

    cid         name  type  notnull dflt_value  pk
0     0         Make  TEXT        0       None   0
1     1        Model  TEXT        0       None   0
2     2         Type  TEXT        0       None   0
3     3       Origin  TEXT        0       None   0
4     4   DriveTrain  TEXT        0       None   0
5     5         MSRP  TEXT        0       None   0
6     6      Invoice  TEXT        0       None   0
7     7   EngineSize  REAL        0       None   0
8     8    Cylinders  REAL        0       None   0
9     9   Horsepower  REAL        0       None   0
10   10     MPG_City  REAL        0       None   0
11   11  MPG_Highway  REAL        0       None   0
12   12       Weight  REAL        0       None   0
13   13    Wheelbase  REAL        0       None   0
14   14       Length  REAL        0       None   0

#unique cars manufacturer

In [31]:
pd.read_sql_query("""
SELECT COUNT(DISTINCT Make) AS Total_Makes
FROM cars;
""", conn)

   Total_Makes
0           38

#cars by manufacturer

In [32]:
pd.read_sql_query("""
SELECT
    Make,
    COUNT(*) AS Total_Cars
FROM cars
GROUP BY Make
ORDER BY Total_Cars DESC;
""", conn)

             Make  Total_Cars
0          Toyota          28
1       Chevrolet          27
2   Mercedes-Benz          26
3            Ford          23
4             BMW          20
5            Audi          19
6          Nissan          17
7           Honda          17
8      Volkswagen          15
9        Chrysler          15
10     Mitsubishi          13
11          Dodge          13
12          Volvo          12
13         Jaguar          12
14        Hyundai          12
15         Subaru          11
16        Pontiac          11
17          Mazda          11
18          Lexus          11
19            Kia          11
20        Mercury           9
21        Lincoln           9
22          Buick           9
23         Suzuki           8
24         Saturn           8
25       Infiniti           8
26            GMC           8
27       Cadillac           8
28           Saab           7
29        Porsche           7
30          Acura           7
31           None           4
32     Oldsmobile           3
33     Land Rover           3
34           Jeep           3
35          Scion           2
36           MINI           2
37          Isuzu           2
38         Hummer           1

#Cars by Type

In [33]:
pd.read_sql_query("""
SELECT
    Type,
    COUNT(*) AS Total_Cars
FROM cars
GROUP BY Type
ORDER BY Total_Cars DESC;
""", conn)

     Type  Total_Cars
0   Sedan         262
1     SUV          60
2  Sports          49
3   Wagon          30
4   Truck          24
5    None           4
6  Hybrid           3

#Cars by Origin

In [34]:
pd.read_sql_query("""
SELECT
    Origin,
    COUNT(*) AS Total_Cars
FROM cars
GROUP BY Origin
ORDER BY Total_Cars DESC;
""", conn)

   Origin  Total_Cars
0    Asia         158
1     USA         147
2  Europe         123
3    None           4

#drive train analysis

In [35]:
pd.read_sql_query("""
SELECT
    DriveTrain,
    COUNT(*) AS Total_Cars
FROM cars
GROUP BY DriveTrain
ORDER BY Total_Cars DESC;
""", conn)

  DriveTrain  Total_Cars
0      Front         226
1       Rear         110
2        All          92
3       None           4

#Average Horsepower

In [36]:
pd.read_sql_query("""
SELECT
    AVG(Horsepower) AS Avg_Horsepower
FROM cars;
""", conn)

   Avg_Horsepower
0      215.885514

#Maximum Horsepower cars

In [37]:
pd.read_sql_query("""
SELECT
    Make,
    Model,
    Horsepower
FROM cars
ORDER BY Horsepower DESC
LIMIT 10;
""", conn)

            Make                         Model  Horsepower
0          Dodge  Viper SRT-10 convertible 2dr       500.0
1  Mercedes-Benz                     CL600 2dr       493.0
2  Mercedes-Benz                  SL55 AMG 2dr       493.0
3  Mercedes-Benz         SL600 convertible 2dr       493.0
4        Porsche                   911 GT2 2dr       477.0
5           Audi                      RS 6 4dr       450.0
6     Volkswagen               Phaeton W12 4dr       420.0
7         Jaguar                  S-Type R 4dr       390.0
8         Jaguar                       XJR 4dr       390.0
9         Jaguar                 XKR coupe 2dr       390.0

#Minimum Horsepower cars

In [38]:
pd.read_sql_query("""
SELECT
    Make,
    Model,
    Horsepower
FROM cars
ORDER BY Horsepower ASC
LIMIT 10;
""", conn)

         Make                                   Model  Horsepower
0        None                                    None         NaN
1        None                                    None         NaN
2        None                                    None         NaN
3        None                                    None         NaN
4       Honda              Insight 2dr (gas/electric)        73.0
5       Honda  Civic Hybrid 4dr manual (gas/electric)        93.0
6  Volkswagen                       Jetta GLS TDI 4dr       100.0
7   Chevrolet                                Aveo 4dr       103.0
8   Chevrolet                       Aveo LS 4dr hatch       103.0
9     Hyundai                        Accent 2dr hatch       103.0

#Average MPG

In [39]:
pd.read_sql_query("""
SELECT
    AVG(MPG_City) AS Avg_City_MPG,
    AVG(MPG_Highway) AS Avg_Highway_MPG
FROM cars;
""", conn)

   Avg_City_MPG  Avg_Highway_MPG
0     20.060748        26.843458

#Best fuel-efficient cars

In [40]:
pd.read_sql_query("""
SELECT
    Make,
    Model,
    MPG_City,
    MPG_Highway
FROM cars
ORDER BY MPG_Highway DESC
LIMIT 10;
""", conn)

         Make                                   Model  MPG_City  MPG_Highway
0       Honda              Insight 2dr (gas/electric)      60.0         66.0
1       Honda  Civic Hybrid 4dr manual (gas/electric)      46.0         51.0
2      Toyota                Prius 4dr (gas/electric)      59.0         51.0
3  Volkswagen                       Jetta GLS TDI 4dr      38.0         46.0
4       Honda                            Civic HX 2dr      36.0         44.0
5      Toyota                         Echo 2dr manual      35.0         43.0
6      Toyota                                Echo 4dr      35.0         43.0
7      Toyota                          Corolla CE 4dr      32.0         40.0
8      Toyota                           Corolla S 4dr      32.0         40.0
9      Toyota                          Corolla LE 4dr      32.0         40.0

#Average price — MSRP

In [41]:
pd.read_sql_query("""
SELECT
    AVG(CAST(REPLACE(TRIM(MSRP), '$', '') AS REAL)) AS Average_MSRP
FROM cars;
""", conn)

   Average_MSRP
0     32.228972

#Most expensive cars

In [42]:
pd.read_sql_query("""
SELECT
    Make,
    Model,
    MSRP
FROM cars
ORDER BY CAST(REPLACE(TRIM(MSRP), '$', '') AS REAL) DESC
LIMIT 10;
""", conn)

            Make                   Model       MSRP
0        Porsche             911 GT2 2dr  $192,465
1  Mercedes-Benz               CL600 2dr  $128,420
2  Mercedes-Benz   SL600 convertible 2dr  $126,670
3  Mercedes-Benz            SL55 AMG 2dr  $121,770
4  Mercedes-Benz               CL500 2dr   $94,820
5  Mercedes-Benz   SL500 convertible 2dr   $90,520
6          Acura  NSX coupe 2dr manual S   $89,765
7         Jaguar     XKR convertible 2dr   $86,995
8  Mercedes-Benz                S500 4dr   $86,970
9           Audi                RS 6 4dr   $84,600

#Cheapest cars

In [43]:
pd.read_sql_query("""
SELECT
    Make,
    Model,
    MSRP
FROM cars
ORDER BY CAST(REPLACE(TRIM(MSRP), '$', '') AS REAL) ASC
LIMIT 10;
""", conn)

        Make             Model      MSRP
0       None              None      None
1       None              None      None
2       None              None      None
3       None              None      None
4    Hyundai  Accent 2dr hatch  $10,539
5        Kia    Rio 4dr manual  $10,280
6     Saturn          Ion1 4dr  $10,995
7     Toyota   Echo 2dr manual  $10,760
8  Chevrolet          Aveo 4dr  $11,690
9    Hyundai     Accent GL 4dr  $11,839

#Average price by manufacturer

In [44]:
pd.read_sql_query("""
SELECT
    Make,
    COUNT(*) AS Total_Cars,
    ROUND(AVG(CAST(REPLACE(TRIM(MSRP), '$', '') AS REAL)), 2) AS Avg_MSRP
FROM cars
GROUP BY Make
ORDER BY Avg_MSRP DESC;
""", conn)

             Make  Total_Cars  Avg_MSRP
0         Porsche           7     83.14
1          Jaguar          12     60.67
2   Mercedes-Benz          26     60.12
3        Cadillac           8     49.75
4          Hummer           1     49.00
5      Land Rover           3     45.33
6           Lexus          11     43.82
7             BMW          20     42.75
8            Audi          19     42.74
9           Acura           7     42.29
10        Lincoln           9     42.22
11           Saab           7     37.14
12          Volvo          12     35.83
13       Infiniti           8     35.50
14     Volkswagen          15     31.87
15          Buick           9     30.00
16            GMC           8     29.00
17        Mercury           9     27.22
18       Chrysler          15     26.73
19      Chevrolet          27     26.07
20          Dodge          13     25.77
21          Isuzu           2     25.50
22         Subaru          11     25.00
23         Nissan          17     24.12
24           Jeep           3     24.00
25        Pontiac          11     23.64
26           Ford          23     23.57
27     Oldsmobile           3     23.00
28     Mitsubishi          13     22.92
29         Toyota          28     21.93
30          Mazda          11     21.36
31          Honda          17     20.88
32           MINI           2     17.50
33        Hyundai          12     16.92
34         Saturn           8     16.63
35         Suzuki           8     15.75
36            Kia          11     15.45
37          Scion           2     13.00
38           None           4       NaN

#Average horsepower by Type

In [45]:
pd.read_sql_query("""
SELECT
    Type,
    COUNT(*) AS Total_Cars,
    ROUND(AVG(Horsepower), 2) AS Avg_Horsepower
FROM cars
GROUP BY Type
ORDER BY Avg_Horsepower DESC;
""", conn)

     Type  Total_Cars  Avg_Horsepower
0  Sports          49          284.16
1     SUV          60          235.82
2   Truck          24          224.83
3   Sedan         262          201.66
4   Wagon          30          194.00
5  Hybrid           3           92.00
6    None           4             NaN

#Top 10 heaviest cars

In [46]:
pd.read_sql_query("""
SELECT
    Make,
    Model,
    Weight
FROM cars
ORDER BY Weight DESC
LIMIT 10;
""", conn)

            Make                  Model  Weight
0           Ford      Excursion 6.8 XLT  7190.0
1         Hummer                     H2  6400.0
2            GMC      Yukon XL 2500 SLT  6133.0
3        Lincoln       Navigator Luxury  5969.0
4       Cadillac           Escalade EXT  5879.0
5      Chevrolet         Avalanche 1500  5678.0
6          Lexus                 LX 470  5590.0
7           Ford  F-150 Supercab Lariat  5464.0
8            GMC         Sierra HD 2500  5440.0
9  Mercedes-Benz                   G500  5423.0

#Database close

In [47]:
conn.close()