In [1]:
import pandas as pd

In [2]:
from google.colab import files

In [3]:
uploaded=files.upload()

Saving sales_store_updated_allign_with_video.csv to sales_store_updated_allign_with_video.csv

In [5]:
df=pd.read_csv('sales_store_updated_allign_with_video.csv')
df

,transaction_id,customer_id,customer_name,customer_age,gender,product_id,product_name,product_category,quantiy,prce,payment_mode,purchase_date,time_of_purchase,status
0,TXN886726,CUST4481,Dhanush Bhakta,41.0,F,P8464,Sofa,Furniture,5,21410,UPI,29/08/2023,8:16:22,pending
1,TXN941069,CUST9221,Anahita Shenoy,46.0,F,P7932,Sunglasses,Accessories,2,1156,Cash,04/06/2023,16:24:21,pending
2,TXN132714,CUST9088,Samaira Bora,29.0,Female,P9223,Sunglasses,Accessories,4,13828,UPI,16/09/2023,17:36:13,cancelled
3,TXN855235,CUST5938,Yashvi Sachar,44.0,Male,P6308,Smartwatch,Electronics,3,11214,EMI,26/08/2023,16:59:09,delivered
4,TXN570157,CUST1985,Rhea Manda,45.0,Female,P5718,Wardrobe,Furniture,4,6120,EMI,23/11/2023,0:43:18,delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000,TXN194804,CUST1534,Manjari Sachar,51.0,Female,P2998,Novel,Books,4,15688,UPI,26/10/2023,7:57:34,delivered
2001,TXN801958,CUST7264,Jayesh Bandi,30.0,M,P7596,Bed,Furniture,3,1818,Debit Card,15/05/2023,5:35:26,delivered
2002,TXN416394,CUST3887,Amani Shukla,25.0,M,P4981,Watch,Accessories,4,19908,Cash,05/03/2023,15:12:22,pending
2003,TXN541709,CUST8436,Siya Mane,39.0,Male,P9301,Belt,Accessories,1,2721,Cash,17/09/2023,2:50:59,returned
2004,TXN814419,CUST9709,Suhana Sule,26.0,M,P1106,Notebook,Books,5,3165,Credit Card,08/06/2023,21:01:59,returned

In [8]:
df.shape

(2005, 14)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2005 entries, 0 to 2004
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    2004 non-null   object
 1   customer_id       2002 non-null   object
 2   customer_name     2003 non-null   object
 3   customer_age      2003 non-null   float64
 4   gender            2003 non-null   object
 5   product_id        2005 non-null   object
 6   product_name      2005 non-null   object
 7   product_category  2005 non-null   object
 8   quantiy           2005 non-null   int64
 9   prce              2005 non-null   int64
 10  payment_mode      2004 non-null   object
 11  purchase_date     2004 non-null   object
 12  time_of_purchase  2004 non-null   object
 13  status            2004 non-null   object
dtypes: float64(1), int64(2), object(11)
memory usage: 219.4+ KB

In [9]:
df.columns

Index(['transaction_id', 'customer_id', 'customer_name', 'customer_age',
       'gender', 'product_id', 'product_name', 'product_category', 'quantiy',
       'prce', 'payment_mode', 'purchase_date', 'time_of_purchase', 'status'],
      dtype='object')

In [10]:
df.isnull().sum()

transaction_id      1
customer_id         3
customer_name       2
customer_age        2
gender              2
product_id          0
product_name        0
product_category    0
quantiy             0
prce                0
payment_mode        1
purchase_date       1
time_of_purchase    1
status              1
dtype: int64

In [12]:
df.dropna(subset=['transaction_id','customer_id','customer_name','customer_age','gender','payment_mode','purchase_date','time_of_purchase','status'],inplace=True)

In [13]:
df.duplicated().sum()

np.int64(4)

In [15]:
df.drop_duplicates()

,transaction_id,customer_id,customer_name,customer_age,gender,product_id,product_name,product_category,quantiy,prce,payment_mode,purchase_date,time_of_purchase,status
0,TXN886726,CUST4481,Dhanush Bhakta,41.0,F,P8464,Sofa,Furniture,5,21410,UPI,29/08/2023,8:16:22,pending
1,TXN941069,CUST9221,Anahita Shenoy,46.0,F,P7932,Sunglasses,Accessories,2,1156,Cash,04/06/2023,16:24:21,pending
2,TXN132714,CUST9088,Samaira Bora,29.0,Female,P9223,Sunglasses,Accessories,4,13828,UPI,16/09/2023,17:36:13,cancelled
3,TXN855235,CUST5938,Yashvi Sachar,44.0,Male,P6308,Smartwatch,Electronics,3,11214,EMI,26/08/2023,16:59:09,delivered
4,TXN570157,CUST1985,Rhea Manda,45.0,Female,P5718,Wardrobe,Furniture,4,6120,EMI,23/11/2023,0:43:18,delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000,TXN194804,CUST1534,Manjari Sachar,51.0,Female,P2998,Novel,Books,4,15688,UPI,26/10/2023,7:57:34,delivered
2001,TXN801958,CUST7264,Jayesh Bandi,30.0,M,P7596,Bed,Furniture,3,1818,Debit Card,15/05/2023,5:35:26,delivered
2002,TXN416394,CUST3887,Amani Shukla,25.0,M,P4981,Watch,Accessories,4,19908,Cash,05/03/2023,15:12:22,pending
2003,TXN541709,CUST8436,Siya Mane,39.0,Male,P9301,Belt,Accessories,1,2721,Cash,17/09/2023,2:50:59,returned
2004,TXN814419,CUST9709,Suhana Sule,26.0,M,P1106,Notebook,Books,5,3165,Credit Card,08/06/2023,21:01:59,returned

In [17]:
df.describe()

       customer_age      quantiy          prce
count   2001.000000  2001.000000   2001.000000
mean      38.904048     3.042479   7949.626687
std       12.628729     1.412337   6045.296384
min       18.000000     1.000000    101.000000
25%       28.000000     2.000000   2948.000000
50%       39.000000     3.000000   6634.000000
75%       50.000000     4.000000  11742.000000
max       60.000000     5.000000  24985.000000

#import sql

In [19]:
import pandas as pd
import sqlite3

In [22]:
df=pd.read_csv('sales_store_updated_allign_with_video.csv')
df

,transaction_id,customer_id,customer_name,customer_age,gender,product_id,product_name,product_category,quantiy,prce,payment_mode,purchase_date,time_of_purchase,status
0,TXN886726,CUST4481,Dhanush Bhakta,41.0,F,P8464,Sofa,Furniture,5,21410,UPI,29/08/2023,8:16:22,pending
1,TXN941069,CUST9221,Anahita Shenoy,46.0,F,P7932,Sunglasses,Accessories,2,1156,Cash,04/06/2023,16:24:21,pending
2,TXN132714,CUST9088,Samaira Bora,29.0,Female,P9223,Sunglasses,Accessories,4,13828,UPI,16/09/2023,17:36:13,cancelled
3,TXN855235,CUST5938,Yashvi Sachar,44.0,Male,P6308,Smartwatch,Electronics,3,11214,EMI,26/08/2023,16:59:09,delivered
4,TXN570157,CUST1985,Rhea Manda,45.0,Female,P5718,Wardrobe,Furniture,4,6120,EMI,23/11/2023,0:43:18,delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2000,TXN194804,CUST1534,Manjari Sachar,51.0,Female,P2998,Novel,Books,4,15688,UPI,26/10/2023,7:57:34,delivered
2001,TXN801958,CUST7264,Jayesh Bandi,30.0,M,P7596,Bed,Furniture,3,1818,Debit Card,15/05/2023,5:35:26,delivered
2002,TXN416394,CUST3887,Amani Shukla,25.0,M,P4981,Watch,Accessories,4,19908,Cash,05/03/2023,15:12:22,pending
2003,TXN541709,CUST8436,Siya Mane,39.0,Male,P9301,Belt,Accessories,1,2721,Cash,17/09/2023,2:50:59,returned
2004,TXN814419,CUST9709,Suhana Sule,26.0,M,P1106,Notebook,Books,5,3165,Credit Card,08/06/2023,21:01:59,returned

In [23]:
conn = sqlite3.connect("sales_store.db")

df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Data successfully inserted into SQLite!")

Data successfully inserted into SQLite!

In [24]:
query = "SELECT * FROM sales LIMIT 10"

result = pd.read_sql_query(query, conn)

result

,transaction_id,customer_id,customer_name,customer_age,gender,product_id,product_name,product_category,quantiy,prce,payment_mode,purchase_date,time_of_purchase,status
0,TXN886726,CUST4481,Dhanush Bhakta,41.0,F,P8464,Sofa,Furniture,5,21410,UPI,29/08/2023,8:16:22,pending
1,TXN941069,CUST9221,Anahita Shenoy,46.0,F,P7932,Sunglasses,Accessories,2,1156,Cash,04/06/2023,16:24:21,pending
2,TXN132714,CUST9088,Samaira Bora,29.0,Female,P9223,Sunglasses,Accessories,4,13828,UPI,16/09/2023,17:36:13,cancelled
3,TXN855235,CUST5938,Yashvi Sachar,44.0,Male,P6308,Smartwatch,Electronics,3,11214,EMI,26/08/2023,16:59:09,delivered
4,TXN570157,CUST1985,Rhea Manda,45.0,Female,P5718,Wardrobe,Furniture,4,6120,EMI,23/11/2023,0:43:18,delivered
5,TXN539308,CUST4895,Shaan Wali,47.0,M,P4430,Sweater,Clothing,1,1877,UPI,05/08/2023,12:50:42,cancelled
6,TXN812961,CUST8436,Siya Mane,39.0,Male,P1599,Vegetables,Groceries,4,7564,EMI,08/12/2023,11:27:03,returned
7,TXN217458,CUST9221,Anahita Shenoy,46.0,F,P3359,Dining Table,Furniture,5,14240,UPI,13/08/2023,18:47:24,pending
8,TXN352074,CUST9479,Nehmat Choudhary,49.0,Male,P2105,Fruits,Groceries,4,19380,Debit Card,12/09/2023,20:52:07,pending
9,TXN965428,CUST1799,Damini Bhalla,38.0,M,P4692,Sofa,Furniture,1,162,Cash,12/09/2023,2:35:57,returned

In [25]:
pd.read_sql_query(
    "SELECT COUNT(*) AS total_records FROM sales",
    conn
)

   total_records
0           2005

#Category-wise sales quantity:

In [26]:
query = """
SELECT product_category,
       SUM(quantiy) AS total_quantity
FROM sales
GROUP BY product_category
ORDER BY total_quantity DESC;
"""

pd.read_sql_query(query, conn)

  product_category  total_quantity
0         Clothing            1106
1        Furniture            1017
2        Groceries            1009
3      Accessories            1009
4            Books            1008
5      Electronics             954

#Payment mode analysis:

In [27]:
query = """
SELECT payment_mode,
       COUNT(*) AS transactions
FROM sales
GROUP BY payment_mode
ORDER BY transactions DESC;
"""

pd.read_sql_query(query, conn)

  payment_mode  transactions
0          EMI           351
1   Debit Card           344
2           CC           338
3         Cash           334
4          UPI           327
5  Credit Card           310
6         None             1

#Status-wise transactions:

In [28]:
query = """
SELECT status,
       COUNT(*) AS total_transactions
FROM sales
GROUP BY status;
"""

pd.read_sql_query(query, conn)

      status  total_transactions
0       None                   1
1  cancelled                 486
2  delivered                 478
3    pending                 540
4   returned                 500

#Top 10 products:

In [29]:
query = """
SELECT product_name,
       SUM(quantiy) AS total_quantity
FROM sales
GROUP BY product_name
ORDER BY total_quantity DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  product_name  total_quantity
0   Vegetables             253
1     Notebook             235
2      Sweater             229
3      T-Shirt             228
4        Chair             228
5     Wardrobe             227
6       Jacket             227
7         Belt             222
8        Shirt             220
9   Smartphone             217